[package]
name = "tungsten-kb"
description = "tungsten's compiled-in knowledge base (constants, elements, items)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tungsten-units.workspace = true

[lints]
workspace = true
