//! Compiles data/units.toml into static lookup tables.
//!
//! Fails the build when an entry has no source, names an unknown system or
//! base dimension, or when two units (or a unit and a prefixed unit) answer to
//! the same symbol or name. Definitions themselves are resolved at run time and
//! checked by the crate's tests.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct File {
    prefix: Vec<Prefix>,
    unit: Vec<Unit>,
    quantity: Vec<Quantity>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Prefix {
    symbol: String,
    name: String,
    factor: String,
    kind: String,
    #[serde(default)]
    aliases: Vec<String>,
    source: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Unit {
    names: Vec<String>,
    plurals: Option<Vec<String>>,
    #[serde(default)]
    symbols: Vec<String>,
    display: Option<String>,
    base: Option<String>,
    scale: Option<String>,
    def: Option<String>,
    offset: Option<String>,
    delta: Option<String>,
    prefixes: Option<String>,
    #[serde(default)]
    expand: bool,
    system: String,
    source: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Quantity {
    name: String,
    dim: String,
    derived: Option<String>,
    groups: Vec<Vec<String>>,
    #[serde(default)]
    extra: Vec<Vec<String>>,
}

const SYSTEMS: &[(&str, &str)] = &[
    ("si", "Si"),
    ("metric", "Metric"),
    ("imperial", "Imperial"),
    ("us", "Us"),
    ("nautical", "Nautical"),
    ("astronomical", "Astronomical"),
    ("information", "Information"),
    ("physics", "Physics"),
    ("other", "Other"),
];

const BASES: &[(&str, &str)] = &[
    ("length", "Length"),
    ("mass", "Mass"),
    ("time", "Time"),
    ("current", "Current"),
    ("temperature", "Temperature"),
    ("amount", "Amount"),
    ("luminosity", "Luminosity"),
    ("currency", "Currency"),
    ("information", "Information"),
    ("count", "Count"),
];

const LARGE: &[&str] = &["k", "M", "G", "T", "P", "E", "Z", "Y", "R", "Q"];

fn pluralize(name: &str) -> String {
    let b = name.as_bytes();
    let n = b.len();
    if name.ends_with('s')
        || name.ends_with('x')
        || name.ends_with('z')
        || name.ends_with("ch")
        || name.ends_with("sh")
    {
        format!("{name}es")
    } else if n > 1 && b[n - 1] == b'y' && !b"aeiou".contains(&b[n - 2]) {
        format!("{}ies", &name[..n - 1])
    } else {
        format!("{name}s")
    }
}

fn fail(msg: String) -> ! {
    panic!("\n\ndata/units.toml: {msg}\n\n");
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let path = manifest.join("../../data/units.toml");
    println!("cargo:rerun-if-changed={}", path.display());
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| fail(format!("cannot read {}: {e}", path.display())));
    let file: File = toml::from_str(&text).unwrap_or_else(|e| fail(e.to_string()));

    // Prefix sets.
    let si: Vec<usize> = (0..file.prefix.len())
        .filter(|&i| file.prefix[i].kind == "si")
        .collect();
    let binary: Vec<usize> = (0..file.prefix.len())
        .filter(|&i| file.prefix[i].kind == "binary")
        .collect();
    for p in &file.prefix {
        if p.source.trim().is_empty() {
            fail(format!("prefix {} has no source", p.symbol));
        }
        if p.kind != "si" && p.kind != "binary" {
            fail(format!("prefix {} has unknown kind {}", p.symbol, p.kind));
        }
    }
    let prefix_index = |sym: &str| -> usize {
        file.prefix
            .iter()
            .position(|p| p.symbol == sym)
            .unwrap_or_else(|| fail(format!("unknown prefix {sym}")))
    };

    let mut out = String::new();
    out.push_str("// Generated by build.rs from data/units.toml. Do not edit.\n\n");

    out.push_str("pub static PREFIXES: &[PrefixDef] = &[\n");
    for p in &file.prefix {
        writeln!(
            out,
            "    PrefixDef {{ symbol: {:?}, name: {:?}, factor: {:?}, source: {:?} }},",
            p.symbol, p.name, p.factor, p.source
        )
        .ok();
    }
    out.push_str("];\n\n");

    // symbol/name -> (unit, prefix); collisions are build errors.
    let mut symbols: BTreeMap<String, (usize, u8)> = BTreeMap::new();
    let mut names: BTreeMap<String, (usize, u8)> = BTreeMap::new();
    let insert = |map: &mut BTreeMap<String, (usize, u8)>, key: String, v: (usize, u8), what| {
        if let Some(prev) = map.get(&key)
            && *prev != v
        {
            let who = |(u, _): (usize, u8)| file.unit[u].names[0].clone();
            fail(format!(
                "{what} {key:?} names both {:?} and {:?}",
                who(*prev),
                who(v)
            ));
        }
        map.insert(key, v);
    };

    out.push_str("pub static UNITS: &[UnitDef] = &[\n");
    for (i, u) in file.unit.iter().enumerate() {
        let label = &u.names[0];
        if u.source.trim().is_empty() {
            fail(format!("unit {label} has no source"));
        }
        let system = SYSTEMS
            .iter()
            .find(|(k, _)| *k == u.system)
            .unwrap_or_else(|| fail(format!("unit {label} has unknown system {}", u.system)))
            .1;
        let def = match (&u.base, &u.def) {
            (Some(b), None) => {
                let base = BASES
                    .iter()
                    .find(|(k, _)| k == b)
                    .unwrap_or_else(|| fail(format!("unit {label} has unknown base {b}")))
                    .1;
                format!(
                    "Def::Base {{ dim: BaseDim::{base}, scale: {:?} }}",
                    u.scale.as_deref().unwrap_or("1")
                )
            }
            (None, Some(d)) => format!("Def::Expr({d:?})"),
            _ => fail(format!(
                "unit {label} needs exactly one of `base` and `def`"
            )),
        };
        if u.offset.is_some() != u.delta.is_some() {
            fail(format!("unit {label}: `offset` and `delta` go together"));
        }
        for n in &u.names {
            if n.to_lowercase() != *n {
                fail(format!("unit {label}: name {n:?} must be lowercase"));
            }
        }
        let plurals: Vec<String> = match &u.plurals {
            Some(p) => p.clone(),
            None => u.names.iter().map(|n| pluralize(n)).collect(),
        };
        let display = u
            .display
            .clone()
            .or_else(|| u.symbols.first().cloned())
            .unwrap_or_else(|| u.names[0].clone());
        let prefixes: Vec<usize> = match u.prefixes.as_deref() {
            None => vec![],
            Some(spec) => spec
                .split_whitespace()
                .flat_map(|w| match w {
                    "si" => si.clone(),
                    "binary" => binary.clone(),
                    "large" => LARGE.iter().map(|s| prefix_index(s)).collect(),
                    other => vec![prefix_index(other)],
                })
                .collect(),
        };
        let mask: u64 = prefixes.iter().fold(0, |m, &p| m | (1 << p));
        writeln!(
            out,
            "    UnitDef {{ name: {:?}, plural: {:?}, display: {:?}, def: {def}, offset: {:?}, \
             delta: {:?}, prefixes: {mask}, expand: {}, system: System::{system}, source: {:?} }},",
            u.names[0], plurals[0], display, u.offset, u.delta, u.expand, u.source
        )
        .ok();

        for s in &u.symbols {
            insert(&mut symbols, s.clone(), (i, 255), "symbol");
            for &p in &prefixes {
                let pf = &file.prefix[p];
                for ps in std::iter::once(&pf.symbol).chain(&pf.aliases) {
                    // Word aliases (deka) are names, not symbols.
                    if ps.chars().count() <= 2 {
                        insert(&mut symbols, format!("{ps}{s}"), (i, p as u8), "symbol");
                    }
                }
            }
        }
        for n in u.names.iter().chain(&plurals) {
            insert(&mut names, n.clone(), (i, 255), "name");
            for &p in &prefixes {
                let pf = &file.prefix[p];
                let words = std::iter::once(&pf.name)
                    .chain(pf.aliases.iter().filter(|a| a.chars().count() > 2));
                for pn in words {
                    insert(&mut names, format!("{pn}{n}"), (i, p as u8), "name");
                }
            }
        }
    }
    out.push_str("];\n\n");

    // A name must not shadow a symbol of a different unit: `min` is a symbol,
    // and must not also be some unit's name.
    for (k, v) in &names {
        if let Some(s) = symbols.get(k)
            && s != v
        {
            fail(format!(
                "{k:?} is a symbol of {:?} and a name of {:?}",
                file.unit[s.0].names[0], file.unit[v.0].names[0]
            ));
        }
    }

    for (label, map) in [("SYMBOLS", &symbols), ("NAMES", &names)] {
        writeln!(out, "pub static {label}: &[(&str, u16, u8)] = &[").ok();
        for (k, (u, p)) in map {
            writeln!(out, "    ({k:?}, {u}, {p}),").ok();
        }
        out.push_str("];\n\n");
    }

    out.push_str("pub static QUANTITIES: &[QuantityDef] = &[\n");
    for q in &file.quantity {
        let list = |g: &Vec<Vec<String>>| {
            let inner: Vec<String> = g.iter().map(|v| format!("&{v:?}")).collect();
            format!("&[{}]", inner.join(", "))
        };
        writeln!(
            out,
            "    QuantityDef {{ name: {:?}, dim: {:?}, derived: {:?}, groups: {}, extra: {} }},",
            q.name,
            q.dim,
            q.derived,
            list(&q.groups),
            list(&q.extra)
        )
        .ok();
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("out dir")).join("units.rs");
    std::fs::write(dest, out).expect("write generated table");
}
