#!/usr/bin/env python3
"""Generates data/constants.toml from NIST's CODATA 2022 listing.

    python3 scripts/data/codata.py            # fetches the listing
    python3 scripts/data/codata.py allascii.txt

Every constant in the adjustment becomes an entity with one property, `value`,
and its standard uncertainty. The only hand-written part is ALIASES below: the
conventional short symbols and everyday names for the constants people type.
"""

import re
import sys
import urllib.request
from pathlib import Path

URL = "https://physics.nist.gov/cuu/Constants/Table/allascii.txt"
OUT = Path(__file__).resolve().parents[2] / "data" / "constants.toml"
SOURCE = "CODATA 2022 (NIST, physics.nist.gov/cuu/Constants)"

# Official name -> (symbols, extra names). Symbols are case-sensitive; names
# are matched case-insensitively. A symbol that is also a unit or a math
# constant (h, e, F, c) is kept but shadowed: reachable with --as constant.
ALIASES = {
    "speed of light in vacuum": (["c"], ["speed of light"]),
    "Newtonian constant of gravitation": (["G"], ["gravitational constant", "newton's constant", "big g"]),
    "Planck constant": (["h", "ℎ"], ["planck's constant"]),
    "reduced Planck constant": (["ħ", "hbar", "h_bar"], ["h-bar", "dirac constant"]),
    "Boltzmann constant": (["k_B", "kB"], ["boltzmann's constant"]),
    "Avogadro constant": (["N_A", "NA"], ["avogadro's number", "avogadro number"]),
    "elementary charge": (["e", "q_e"], ["charge of an electron", "electron charge"]),
    "electron mass": (["m_e"], ["mass of an electron"]),
    "proton mass": (["m_p"], ["mass of a proton"]),
    "neutron mass": (["m_n"], ["mass of a neutron"]),
    "atomic mass constant": (["m_u"], []),
    "fine-structure constant": (["α", "alpha"], ["fine structure constant"]),
    "Rydberg constant": (["R_inf", "R∞"], []),
    "Bohr radius": (["a_0", "a0", "a₀"], []),
    "molar gas constant": (["R"], ["gas constant", "ideal gas constant", "universal gas constant"]),
    "Faraday constant": (["F"], []),
    "Stefan-Boltzmann constant": (["σ", "sigma"], ["stefan boltzmann constant"]),
    "vacuum electric permittivity": (["ε0", "ε₀", "epsilon_0", "eps0"], ["vacuum permittivity", "permittivity of free space", "electric constant"]),
    "vacuum mag. permeability": (["μ0", "μ₀", "mu_0", "mu0"], ["vacuum permeability", "permeability of free space", "magnetic constant", "vacuum magnetic permeability"]),
    "Bohr magneton": (["μ_B", "mu_B"], []),
    "standard acceleration of gravity": (["g_n"], []),
    "standard atmosphere": (["atm"], ["atmosphere"]),
    "Wien wavelength displacement law constant": (["b_wien"], ["wien's constant", "wien constant"]),
    "characteristic impedance of vacuum": (["Z_0", "Z0"], ["impedance of free space"]),
    "Hartree energy": (["E_h"], []),
    "electron volt": (["eV"], []),
}


def clean(s):
    return s.replace(" ", "").replace("...", "")


def main():
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text()
    else:
        text = urllib.request.urlopen(URL).read().decode()
    lines = text.split("\n")
    start = next(i for i, l in enumerate(lines) if l.startswith("-----")) + 1
    rows = [l for l in lines[start:] if l.strip()]

    out = [
        "# data/constants.toml — generated by scripts/data/codata.py. Do not edit;",
        "# change ALIASES in the script and regenerate.",
        "#",
        f"# The complete {SOURCE} adjustment: {len(rows)} constants.",
        "",
    ]
    seen = set()
    for l in rows:
        name, value, unc, unit = l[:60].strip(), l[60:85], l[85:110].strip(), l[110:].strip()
        symbols, extra = ALIASES.get(name, ([], []))
        seen.add(name)
        value = clean(value)
        unc = "exact" if unc == "(exact)" else clean(unc)
        v = f"{value} {unit}".strip()
        names = [name.lower()] + [n for n in extra if n != name.lower()]
        out.append("[[entity]]")
        out.append('kind = "constant"')
        out.append(f"display = {toml(name)}")
        out.append(f"names = [{', '.join(toml(n) for n in names)}]")
        if symbols:
            out.append(f"symbols = [{', '.join(toml(s) for s in symbols)}]")
        out.append('default = "value"')
        out.append(f"source = {toml(SOURCE)}")
        out.append("[entity.props]")
        out.append(f"value = {toml(v)}")
        out.append("[entity.uncertainty]")
        out.append(f"value = {toml(unc if unc == 'exact' else f'{unc} {unit}'.strip())}")
        out.append("")
    missing = set(ALIASES) - seen
    if missing:
        sys.exit(f"ALIASES names constants not in the listing: {sorted(missing)}")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(rows)} constants)")


def toml(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
