#!/usr/bin/env python3
"""Generates data/elements.toml from PubChem's periodic table.

    python3 scripts/data/elements.py              # fetches the CSV
    python3 scripts/data/elements.py periodic.csv

All 118 elements with atomic number, atomic mass, density, melting and boiling
points, standard state, category and year of discovery. Properties PubChem
does not give (the superheavy elements were never weighed or melted) are left
out rather than guessed. Hand-written: British spellings and etymology notes.
"""

import csv
import io
import sys
import urllib.request
from pathlib import Path

URL = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/CSV"
OUT = Path(__file__).resolve().parents[2] / "data" / "elements.toml"
SOURCE = "PubChem Periodic Table of Elements (NIH), pubchem.ncbi.nlm.nih.gov/periodic-table, retrieved 2026-09-23"

EXTRA_NAMES = {
    "Aluminum": ["aluminium"],
    "Cesium": ["caesium"],
    "Sulfur": ["sulphur"],
    "Tungsten": ["wolfram"],
}

NAMED = {
    "Tungsten": (
        "From Swedish tung sten, 'heavy stone'. Its symbol W is from wolfram, "
        "after the ore wolframite: German Wolf Rahm, 'wolf's froth', because "
        "the ore devoured tin during smelting."
    ),
}


def toml(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text()
    else:
        text = urllib.request.urlopen(URL).read().decode()
    rows = list(csv.DictReader(io.StringIO(text)))
    out = [
        "# data/elements.toml — generated by scripts/data/elements.py. Do not edit;",
        "# change the script and regenerate.",
        "#",
        f"# {len(rows)} elements from {SOURCE}.",
        "# Temperatures are as published, in kelvin; densities in g/cm³ (gases at STP).",
        "",
    ]
    for r in rows:
        name = r["Name"]
        names = [name.lower()] + EXTRA_NAMES.get(name, [])
        out.append("[[entity]]")
        out.append('kind = "element"')
        out.append(f"display = {toml(name.lower())}")
        out.append(f"names = [{', '.join(toml(n) for n in names)}]")
        out.append(f"symbols = [{toml(r['Symbol'])}]")
        out.append(f"source = {toml(SOURCE)}")
        out.append("[entity.props]")
        out.append(f'"atomic number" = "{r["AtomicNumber"]}"')
        out.append(f'"atomic mass" = "{r["AtomicMass"]} u"')
        if r["Density"].strip():
            out.append(f'density = "{r["Density"]} g/cm^3"')
        if r["MeltingPoint"].strip():
            out.append(f'"melting point" = "{r["MeltingPoint"]} K"')
        if r["BoilingPoint"].strip():
            out.append(f'"boiling point" = "{r["BoilingPoint"]} K"')
        out.append("[entity.facts]")
        out.append(f"state = {toml(r['StandardState'].lower())}")
        out.append(f"category = {toml(r['GroupBlock'].lower())}")
        out.append(f"discovered = {toml(r['YearDiscovered'].lower())}")
        if name in NAMED:
            out.append(f"named = {toml(NAMED[name])}")
        out.append("")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(rows)} elements)")


if __name__ == "__main__":
    main()
